config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/log_in', to: 'users/sessions#log_in'
  end

  resources :groups
  resources :entities
  root "groups#index"
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @entities = Entity.where(user: current_user)
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
    @groups = Group.where(user: current_user)
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)
    @entity.user = current_user
    @entity.group = Group.find(params[:group_id])

    respond_to do |format|
      if @entity.save
        format.html { redirect_to group_url(Group.find(params[:group_id])), notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= entity.amount %>
  </p>

</div>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entities</h1>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
    <p>
      <%= link_to "Show this entity", entity %>
    </p>
  <% end %>
</div>

<%= link_to "Add transaction", new_group_path %>

app/views/entities/new.html.erb
<%= form_with(model: @entity, url: "/entities", html: {class: 'forms_container flex_centered_column'}) do |form| %>
  <% if @entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this @entity from being saved:</h2>

      <ul>
        <% @entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% initial_group = nil %>
  <% initial_group = params[:group_id] if params[:group_id]  %>

  <%= select_tag :group_id, options_from_collection_for_select(@groups, :id, :name, initial_group), prompt: "Select one category", required: true, class: "field" %>
  <%= form.text_field :name, placeholder: 'Name', class: "field" %>
  <%= form.text_field :amount, placeholder: 'Amount', class: "field" %>
  <%= form.submit %>
<% end %>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <%= link_to "Edit this entity", edit_entity_path(@entity) %> |
  <%= link_to "Back to entities", entities_path %>

  <%= button_to "Destroy this entity", @entity, method: :delete %>
</div>